DEEPSORT:
  REID_CKPT: "/home/ljq/UAV-Tracking/ultralytics/weights/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100
  

# tracker_type: deepsort
# model_path: "ultralytics/trackers/deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7"


# max_dist: 0.2
# min_confidence: 0.3
# nms_max_overlap: 1.0
# max_iou_distance: 0.7
# max_age: 70
# n_init: 3
# nn_budget: 100